export default [
  { family: 'Abril Fatface', source: 'google' },
  { family: 'Alfa Slab One', source: 'google' },
  { family: 'Amatic SC', source: 'google' },
  { family: 'Anton', source: 'google' },
  { family: 'Arial', source: 'local' },
  { family: 'Assistant', source: 'google' },
  { family: 'Bangers', source: 'google' },
  { family: 'Cabin Sketch', source: 'google' },
  { family: 'Caveat Brush', source: 'google' },
  { family: 'Creepster', source: 'google' },
  { family: 'Crete Round', source: 'google' },
  { family: 'Fjalla One', source: 'google' },
  { family: 'Fredericka the Great', source: 'google' },
  { family: 'Gentium Basic', source: 'google' },
  { family: 'Helvetica', source: 'local' },
  { family: 'Impact', source: 'local' },
  { family: 'Lato', source: 'google' },
  { family: 'Lobster', source: 'google' },
  { family: 'Love Ya Like A Sister', source: 'google' },
  { family: 'Monoton', source: 'google' },
  { family: 'Montserrat', source: 'google' },
  { family: 'Noto Sans', source: 'google' },
  { family: 'Open Sans', source: 'google' },
  { family: 'Oswald', source: 'google' },
  { family: 'Patua One', source: 'google' },
  { family: 'Playfair Display', source: 'google' },
  { family: 'Poppins', source: 'google' },
  { family: 'PT Sans Narrow', source: 'google' },
  { family: 'Quicksand', source: 'google' },
  { family: 'Raleway', source: 'google' },
  { family: 'Roboto', source: 'google' },
  { family: 'Roboto Condensed', source: 'google' },
  { family: 'Rubik', source: 'google' },
  { family: 'Shrikhand', source: 'google' },
  { family: 'Source Sans Pro', source: 'google' },
  { family: 'Suez One', source: 'google' },
  { family: 'Times', source: 'local' },
  { family: 'Titillium Web', source: 'google' },
  { family: 'Varela Round', source: 'google' },
  { family: 'Verdana', source: 'local' },
  { family: 'Yellowtail', source: 'google' },
];
